includes:
  - from_url:
      url: https://raw.githubusercontent.com/ory/xgoreleaser/2161c61a0c0a33644ba6cd28d4b3a7538101981b/build.tmpl.yml

variables:
  brew_name: cli

  brew_description: "Use Ory from the your terminal!"

  buildinfo_hash: "github.com/ory/cli/buildinfo.GitHash"
  buildinfo_tag: "github.com/ory/cli/buildinfo.Version"
  buildinfo_date: "github.com/ory/cli/buildinfo.Time"

project_name: ory
