# This is an example gorelease.yaml file with some sane defaults.
# Make sure to check the documentation at http://gorelease.com
project_name: ory

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go install github.com/markbates/pkger/cmd/pkger
    - pkger

builds:
  -
    id: ory-sqlite-darwin
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/cmd.BuildVersion={{.Tag}} -X github.com/ory/cli/cmd.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/cmd.BuildTime={{.Date}}
      # - "-extldflags '-static'"
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
    goos:
      - darwin

  -
    id: ory-sqlite-linux
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/cmd.BuildVersion={{.Tag}} -X github.com/ory/cli/cmd.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/cmd.BuildTime={{.Date}}
    binary: ory
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
  -
    id: ory-sqlite-linux-libmusl
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/cmd.BuildVersion={{.Tag}} -X github.com/ory/cli/cmd.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/cmd.BuildTime={{.Date}}
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=musl-gcc
    goarch:
      - amd64
    goos:
      - linux
  -
    id: ory-sqlite-windows
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/ory/cli/cmd.BuildVersion={{.Tag}} -X github.com/ory/cli/cmd.BuildGitHash={{.FullCommit}} -X github.com/ory/cli/cmd.BuildTime={{.Date}}
      - "-extldflags '-static'"
    binary: ory
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goarch:
      - amd64
    goos:
      - windows

archives:
  - builds:
    - ory-sqlite-windows
    - ory-sqlite-darwin
    - ory-sqlite-linux
    - ory-sqlite-linux-libmusl
    id: ory-archive
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

brews:
  - github:
      owner: ory
      name: homebrew-ory
    goarm: 6
    ids:
      - ory-archive
    homepage:  https://www.ory.sh
    commit_author:
      name: aeneasr
      email: aeneas@ory.sh

scoop:
  bucket:
    owner: ory
    name: scoop-ory
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: aeneas@ory.sh

release:
  prerelease: auto
